'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Farma.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1_Arrow_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_Arrow_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1_Arrow_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_Arrow_Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property configuration_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configuration_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_Alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control_Panel_Alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dossiers_Config_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dossiers_Config_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dossiers_Panneau_de_configuration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dossiers_Panneau_de_configuration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dossiers_recherches() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dossiers_recherches", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dossiers_utilisateurs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dossiers_utilisateurs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property File() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("File", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Files_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Files_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Blue_Software() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Blue_Software", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Orange() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Yellow_Software() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Yellow_Software", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Font_File_Alt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Font_File_Alt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Floppy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Floppy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Library_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Library_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Open_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Open_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Printers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Printers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LaST__Cobalt__Text_File() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Text_File", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property msn_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msn_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pan_setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pan_setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - unos.
        '''</summary>
        Friend ReadOnly Property text_add() As String
            Get
                Return ResourceManager.GetString("text_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : promet artikla.
        '''</summary>
        Friend ReadOnly Property text_artikli_promet() As String
            Get
                Return ResourceManager.GetString("text_artikli_promet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Da li ste sigurno da želite da izbrišete zapis sa šifrom.
        '''</summary>
        Friend ReadOnly Property text_brisanje() As String
            Get
                Return ResourceManager.GetString("text_brisanje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : dnevni promet.
        '''</summary>
        Friend ReadOnly Property text_dnevni_promet() As String
            Get
                Return ResourceManager.GetString("text_dnevni_promet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - ažuriranje.
        '''</summary>
        Friend ReadOnly Property text_edit() As String
            Get
                Return ResourceManager.GetString("text_edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : analitika.
        '''</summary>
        Friend ReadOnly Property text_fin_analitika() As String
            Get
                Return ResourceManager.GetString("text_fin_analitika", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : kartice.
        '''</summary>
        Friend ReadOnly Property text_fin_kartice() As String
            Get
                Return ResourceManager.GetString("text_fin_kartice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Došlo je do greške prilikom izvršenja naredbe..
        '''</summary>
        Friend ReadOnly Property text_greska() As String
            Get
                Return ResourceManager.GetString("text_greska", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Došlo je do greške. Zahtevana procedura nije izvršena..
        '''</summary>
        Friend ReadOnly Property text_greska1() As String
            Get
                Return ResourceManager.GetString("text_greska1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : intrrna dostavnica izlaz.
        '''</summary>
        Friend ReadOnly Property text_int_dost_izlaz() As String
            Get
                Return ResourceManager.GetString("text_int_dost_izlaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : intrrna dostavnica ulaz.
        '''</summary>
        Friend ReadOnly Property text_int_dost_ulaz() As String
            Get
                Return ResourceManager.GetString("text_int_dost_ulaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : intrrni prenos.
        '''</summary>
        Friend ReadOnly Property text_int_prenos() As String
            Get
                Return ResourceManager.GetString("text_int_prenos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : kalkulacije.
        '''</summary>
        Friend ReadOnly Property text_kalkulacije() As String
            Get
                Return ResourceManager.GetString("text_kalkulacije", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : kontni okvir.
        '''</summary>
        Friend ReadOnly Property text_konta() As String
            Get
                Return ResourceManager.GetString("text_konta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : laboratorijski dnevnik.
        '''</summary>
        Friend ReadOnly Property text_lab_dnevnik() As String
            Get
                Return ResourceManager.GetString("text_lab_dnevnik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : lager lista.
        '''</summary>
        Friend ReadOnly Property text_lager() As String
            Get
                Return ResourceManager.GetString("text_lager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : magacinski interni prenos.
        '''</summary>
        Friend ReadOnly Property text_mip() As String
            Get
                Return ResourceManager.GetString("text_mip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : nalog.
        '''</summary>
        Friend ReadOnly Property text_nalog() As String
            Get
                Return ResourceManager.GetString("text_nalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : naselja.
        '''</summary>
        Friend ReadOnly Property text_naselja() As String
            Get
                Return ResourceManager.GetString("text_naselja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : nivelacija.
        '''</summary>
        Friend ReadOnly Property text_nivelacija() As String
            Get
                Return ResourceManager.GetString("text_nivelacija", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : OBRADAPODA PODATAKA.
        '''</summary>
        Friend ReadOnly Property text_obrada_podataka() As String
            Get
                Return ResourceManager.GetString("text_obrada_podataka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : organizacione jedinice.
        '''</summary>
        Friend ReadOnly Property text_oj() As String
            Get
                Return ResourceManager.GetString("text_oj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : otvorene stavke.
        '''</summary>
        Friend ReadOnly Property text_otvorene_stavke() As String
            Get
                Return ResourceManager.GetString("text_otvorene_stavke", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : partneri.
        '''</summary>
        Friend ReadOnly Property text_partneri() As String
            Get
                Return ResourceManager.GetString("text_partneri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : povezana konta.
        '''</summary>
        Friend ReadOnly Property text_povezana_konta() As String
            Get
                Return ResourceManager.GetString("text_povezana_konta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nije moguće uneti prazan zapis..
        '''</summary>
        Friend ReadOnly Property text_prazan_zapis() As String
            Get
                Return ResourceManager.GetString("text_prazan_zapis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - štampanje.
        '''</summary>
        Friend ReadOnly Property text_print() As String
            Get
                Return ResourceManager.GetString("text_print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : PROIZVODNJA.
        '''</summary>
        Friend ReadOnly Property text_proizvodnja() As String
            Get
                Return ResourceManager.GetString("text_proizvodnja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : ROBNO.
        '''</summary>
        Friend ReadOnly Property text_robno() As String
            Get
                Return ResourceManager.GetString("text_robno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : sastavnice.
        '''</summary>
        Friend ReadOnly Property text_sastavnice() As String
            Get
                Return ResourceManager.GetString("text_sastavnice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - pretraga.
        '''</summary>
        Friend ReadOnly Property text_search() As String
            Get
                Return ResourceManager.GetString("text_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : izlaz.
        '''</summary>
        Friend ReadOnly Property text_spec_izlaz() As String
            Get
                Return ResourceManager.GetString("text_spec_izlaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : ulaza.
        '''</summary>
        Friend ReadOnly Property text_spec_ulaz() As String
            Get
                Return ResourceManager.GetString("text_spec_ulaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : specifikacije.
        '''</summary>
        Friend ReadOnly Property text_specifikacije() As String
            Get
                Return ResourceManager.GetString("text_specifikacije", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : trebovanje.
        '''</summary>
        Friend ReadOnly Property text_tebovanje() As String
            Get
                Return ResourceManager.GetString("text_tebovanje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Da li ste sigurni da želite da izvršite storniranje? Nakon ove operacije nalog će biti proknjižen i zaključan..
        '''</summary>
        Friend ReadOnly Property text_upit_storno() As String
            Get
                Return ResourceManager.GetString("text_upit_storno", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Themes_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Themes_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
